## Formatting datasets

In [28]:
import sqlite3
import pandas as pd
import numpy as np

In [29]:
PATH_TO_REPO = '/Users/daniel.briquez/Documents/git_repos_pessoal/FootballTatics-BackEnd/'

In [30]:
conn = sqlite3.connect(f'{PATH_TO_REPO}/deep_learning_model/data/database.sqlite')
df_tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'", conn)
df_tables
## this dataset is from 9y ago, therefore I will only be using players dataset of 2015 and 2016

                name
0    sqlite_sequence
1  Player_Attributes
2             Player
3              Match
4             League
5            Country
6               Team
7    Team_Attributes

merging datasets df_player and df_player_stats on player_api_id

In [31]:
df_player = pd.read_sql_query("SELECT * FROM Player", conn)
df_player = df_player[['player_api_id','player_name','height','weight']]
df_player_stats = pd.read_sql_query("SELECT * FROM Player_Attributes", conn)

df_merged = pd.merge(df_player, df_player_stats, on='player_api_id')
data_na = df_merged.drop(['id','player_fifa_api_id','date'],axis=1) # drop columns that are not needed
data_na.head(5)

,player_api_id,player_name,height,weight,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,505942,Aaron Appindangoye,182.88,187,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,505942,Aaron Appindangoye,182.88,187,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,505942,Aaron Appindangoye,182.88,187,62.0,66.0,right,medium,medium,49.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,505942,Aaron Appindangoye,182.88,187,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,505942,Aaron Appindangoye,182.88,187,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0

In [32]:
#load a FIFA dataset and keep only relevant columns.
def load_and_prepare_data(file_path) -> pd.DataFrame: 
    
    df = pd.read_csv(file_path)
    
    df = df[['short_name', 'player_positions']].rename(columns={
        "short_name": "Name",
        "player_positions": "Position"
    })
    
    return df

data_fifa15 = load_and_prepare_data(f'{PATH_TO_REPO}/deep_learning_model/data/players_15.csv')
data_fifa16 = load_and_prepare_data(f'{PATH_TO_REPO}/deep_learning_model/data/players_16.csv')

/var/folders/h8/2sygs01x551_3fv66_prptrc0000gn/T/ipykernel_66148/921060315.py:4: DtypeWarning: Columns (104) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/h8/2sygs01x551_3fv66_prptrc0000gn/T/ipykernel_66148/921060315.py:4: DtypeWarning: Columns (104) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

Claning datasets

In [33]:
print('before:',len(data_na))
a = ['_0', None, '5', 'ean', 'o', '1', 'ormal',
       '7', '2', '8', '4', 'tocky', '0', '3', '6', '9', 'es']

b = [None, 'None', 'le', 'norm', 'stoc', 'y']

data_na = data_na[~data_na['defensive_work_rate'].isin(a)]
data_na = data_na[~data_na['attacking_work_rate'].isin(b)]
data = data_na.dropna(axis=0)


print('after',len(data_na))

before: 183978
after 176161

Quantization

In [34]:
data = data.replace({'low': int(0), 'medium': int(1), 'high': int(2)})
data = data.replace({'left': int(0), 'right': int(1)})
data.sample(5)

/var/folders/h8/2sygs01x551_3fv66_prptrc0000gn/T/ipykernel_66148/1206903638.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data = data.replace({'low': int(0), 'medium': int(1), 'high': int(2)})
/var/folders/h8/2sygs01x551_3fv66_prptrc0000gn/T/ipykernel_66148/1206903638.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data = data.replace({'left': int(0), 'right': int(1)})

,player_api_id,player_name,height,weight,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
56751,26078,Flavien La Postollec,180.34,170,67.0,67.0,1,1,1,47.0,...,64.0,54.0,63.0,66.0,64.0,15.0,10.0,13.0,8.0,9.0
47266,107417,Eden Hazard,172.72,163,87.0,92.0,1,2,1,80.0,...,84.0,85.0,25.0,27.0,22.0,11.0,12.0,6.0,8.0,8.0
41102,39435,Davide Di Gennaro,180.34,157,54.0,71.0,1,1,0,38.0,...,70.0,38.0,21.0,21.0,35.0,3.0,21.0,28.0,21.0,21.0
145773,79241,Rafal Grzyb,175.26,165,67.0,67.0,1,1,2,65.0,...,56.0,52.0,61.0,63.0,69.0,8.0,13.0,11.0,8.0,10.0
33780,522750,Dalbert,180.34,163,66.0,74.0,0,2,1,67.0,...,58.0,42.0,68.0,70.0,67.0,7.0,11.0,7.0,9.0,9.0

The dataset has multiples inputs of each player because 1 player might have played multiple matches in different seasons. Therefore, I will remove the duplicates and keep mean values for each player.

In [35]:
# Get numeric columns
numeric_columns = data_na.select_dtypes(include=[np.number]).columns.tolist()

# Check for non-numeric values in numeric columns
for col in numeric_columns:
    # Identify values that cannot be converted to float
    invalid_entries = data_na[~pd.to_numeric(data_na[col], errors='coerce').notnull()][col].unique()
    
    if len(invalid_entries) > 0:
        print(f"Invalid values found in {col}: {invalid_entries}")
        
for col in numeric_columns:
    # Convert problematic values to NaN
    data_na[col] = pd.to_numeric(data_na[col], errors='coerce')

# Now handle NaNs (e.g., drop them or fill with mean/median)
data_na.dropna(subset=numeric_columns, inplace=True)

In [36]:
df_mean = data.groupby(['player_name'],as_index=False).mean()
df_mean.sample(5)

,player_name,player_api_id,height,weight,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
9140,Tom Elliott,49711.0,193.04,183.0,59.666667,67.333333,1.0,1.916667,1.000000,40.250000,...,44.666667,53.666667,19.333333,20.250000,22.750000,12.750000,18.250000,23.083333,13.25000,18.250000
8056,Roland Baettig,34052.0,180.34,154.0,62.000000,64.000000,1.0,1.000000,1.111111,46.555556,...,60.222222,62.555556,65.888889,69.555556,54.888889,13.000000,7.000000,8.000000,15.00000,7.000000
9476,Wellington Silva,202220.0,170.18,150.0,69.000000,80.500000,1.0,1.250000,0.250000,61.437500,...,57.812500,71.625000,19.000000,20.375000,20.875000,14.125000,6.125000,8.125000,7.12500,15.125000
8908,Sylvain Distin,24216.0,193.04,194.0,77.190476,78.095238,0.0,1.000000,2.000000,39.238095,...,56.047619,51.190476,76.523810,78.952381,75.952381,8.904762,10.666667,28.333333,9.47619,9.190476
1776,Curtis Davies,24658.0,187.96,196.0,74.500000,77.392857,1.0,1.000000,1.178571,24.714286,...,54.571429,39.750000,73.714286,76.607143,75.535714,7.857143,10.571429,17.071429,15.25000,11.464286

Changing the names to the same way as it is at the fifa dataset

In [37]:
def Change_names(df):
    player_names = list(df['player_name'].values)

    new_column = []
    for name in player_names:
        complete_name = name.split()

        if len(complete_name) == 1:
            new_column.append(complete_name[0])

        if len(complete_name) != 1:
            nickname = complete_name[1:]
            nickname = " ".join(nickname)
            inicial = complete_name[0][0] + "."
            short_nickname = inicial + " " + str(nickname)
            new_column.append(short_nickname)

    df = df.rename(columns={"player_name": "old_name"})
    df.insert(loc=0, column='Name', value=new_column)
    df = df.drop(['old_name'], axis=1)
    print('Numero de datos totales', len(df))

    return df

df_changed = Change_names(data)
df_changed

Numero de datos totales 176161

,Name,player_api_id,height,weight,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,A. Appindangoye,505942,182.88,187,67.0,71.0,1,1,1,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,A. Appindangoye,505942,182.88,187,67.0,71.0,1,1,1,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,A. Appindangoye,505942,182.88,187,62.0,66.0,1,1,1,49.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,A. Appindangoye,505942,182.88,187,61.0,65.0,1,1,1,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,A. Appindangoye,505942,182.88,187,61.0,65.0,1,1,1,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183973,Z. Misimovic,39902,180.34,176,83.0,85.0,1,1,0,84.0,...,88.0,83.0,22.0,31.0,30.0,9.0,20.0,84.0,20.0,20.0
183974,Z. Misimovic,39902,180.34,176,78.0,80.0,1,1,0,74.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183975,Z. Misimovic,39902,180.34,176,77.0,80.0,1,1,0,74.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183976,Z. Misimovic,39902,180.34,176,78.0,81.0,1,1,0,74.0,...,88.0,53.0,28.0,32.0,30.0,9.0,20.0,73.0,20.0,20.0
183977,Z. Misimovic,39902,180.34,176,80.0,81.0,1,1,0,74.0,...,88.0,53.0,38.0,32.0,30.0,9.0,9.0,78.0,7.0,15.0

In [38]:
df_fifa = pd.merge(data_fifa15, data_fifa16, on='Name', how='inner')
df_fifa = df_fifa.drop(['Position_x'],axis=1)
df_fifa = df_fifa.rename(columns={"Position_y": "Position"})
df_fifa['Position_count'] = df_fifa['Position'].str.split(',').str.len()


# create a new column that counts the number of positions
df_fifa['Position_count'] = df_fifa['Position'].str.split(',').str.len()
idx = df_fifa.groupby('Name')['Position_count'].idxmin()
df_filtered = df_fifa.loc[idx]
# group by Name and get the index of the row with the max Position_count
idx = df_fifa.groupby('Name')['Position_count'].idxmin()
df_filtered_ = df_filtered.drop('Position_count', axis=1)

df_final = pd.merge(df_filtered_, df_changed, on='Name', how='right')
print('Datos Finales:',len(df_final))
df_final.head(6)

Datos Finales: 176161

,Name,Position,player_api_id,height,weight,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,A. Appindangoye,NaN,505942,182.88,187,67.0,71.0,1,1,1,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,A. Appindangoye,NaN,505942,182.88,187,67.0,71.0,1,1,1,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,A. Appindangoye,NaN,505942,182.88,187,62.0,66.0,1,1,1,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,A. Appindangoye,NaN,505942,182.88,187,61.0,65.0,1,1,1,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,A. Appindangoye,NaN,505942,182.88,187,61.0,65.0,1,1,1,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
5,A. Cresswell,LB,155782,170.18,146,74.0,76.0,0,2,1,...,66.0,59.0,76.0,75.0,78.0,14.0,7.0,9.0,9.0,12.0